// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SuiCoinResult {
  coin_type: string;
  coin_id: string;
  balance: number;
}
