// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SuiObjectResult { object_type: string, object_id: string, version: string, digest: string, owner: string, previous_transaction: string, }